spring.application.name=backend
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?useSSL=true&requireSSL=true&verifyServerCertificate=true&useUnicode=true&characterEncoding=utf8
spring.datasource.username=645f1qGNJr81Zte.root
spring.datasource.password=eoP5cOwZSB1mv8Ia
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Optional, if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
